### ISSUE TITLE
How can I warp a struct which is returned from C++ API?

### ISSUE THREAD

**Issue by RuixuanDai** [mbientlab/MetaWear-SDK-JavaScript#1]
Hi,

I want to get the raw stream acceleration data using javascript.  

MetaWear.mbl_mw_datasignal_subscribe(acc_signal, function(acc_signal){
        console.log(typeof(acc_signal));
        console.log(acc_signal);
        console.log(acc_signal.length);
    });

I have get the acc_signal, but it is a object (C++ struct?). I know how to get XYZ values of accelerations in C++. However, what should I do to get the XYZ values in javascript?

**Comment by sschiffli** [comment]
Please take a look at the examples:
https://github.com/mbientlab/MetaWear-SDK-JavaScript/blob/master/examples/multi_device.js#L41

**Comment by RuixuanDai** [comment]
Thanks a lot. Problem solved. But I am really curious about **dataPtr.deref()** .
What does it mean?

**Comment by sschiffli** [comment]
Its part of the "ref" type system, documentation here: http://tootallnate.github.io/ref/

**Comment by RuixuanDai** [comment]
Many thanks to you. Got it!
