### ISSUE TITLE
Parsing DATA_ARRAY data type not working correctly

### ISSUE THREAD

**Issue by Bulion** [mbientlab/MetaWear-SDK-JavaScript#15]
Hello,

While using data fuser (example code), I'm receiving in both acc and gyro same values. Probably this refers to line mentioned by me [here](https://github.com/mbientlab/MetaWear-SDK-JavaScript/commit/bcdb325ced20f6fa6cdd8e07531080eb8e6e8d35#r40093029).

Best regards,
Dawid Śliwa

**Comment by lkasso** [comment]
No actual bug or reproducible steps provided. Closing.

**Comment by Bulion** [comment]
I wrote that this happens when using yours example, data_fuser.js. Just run sudo node data_fuser.js and observe acc and gyro data. It's the same values!
