### ISSUE TITLE
How to warp JS variables into a struct then pass it to C++ API?

### ISSUE THREAD

**Issue by RuixuanDai** [mbientlab/MetaWear-SDK-JavaScript#2]
Hi,
I have another question, Please help me.

I want to warp JS variables into a struct then pass it to C++ API.

To be specific, I want to call the following API in JS.

```
    static MblMwLogDownloadHandler download_handler = { progress_update, unknown_entry };
    // start a log download and send 100 progress notifications
    mbl_mw_logging_download(board, 100, &download_handler);
```

Thanks in advance

**Comment by RuixuanDai** [comment]
Can you give me an example in JS about how to start logging, download logger, and handle the logger? I do not known how to do even after reading the documentation of C++.

Thanks .

**Comment by sschiffli** [comment]
Please see our new example [here](https://github.com/mbientlab/MetaWear-SDK-JavaScript/blob/master/examples/logging.js)

**Comment by RuixuanDai** [comment]
Really appreciate your work. 
Thank you so much.
