### ISSUE TITLE
Using cordova to integrate MetaWear BLE sensor

### ISSUE THREAD

**Issue by wvanooijen92** [mbientlab/MetaWear-SDK-JavaScript#6]
A client asked me to take a look at your sensor. We are evaluating multiple BLE  sensors to use in a mobile application that would be developed using cordova.

Is it possible to use cordova?
Is there a wrapper cordova-plugin available?
Would it be possible to use another cordova BLE plugin like [this](https://github.com/don/cordova-plugin-ble-central)?

**Comment by scaryghost** [comment]
* It is possible to use Cordova though we have not put any effort into Cordova support.  
* There may be some plugins available but they are developed by the community and are probably out of date.  
* As long as that plugin can read/write GATT characteristics and enable notifications, it should be fine.

**Comment by scaryghost** [comment]
We have a community forum (https://mbientlab.com/community/) where we help users get familiar with our supported SDKs and apps, use the hardware, and troubleshoot any issues.  

If you are looking for dedicated support for proprietary projects, you can inquire about a support contract (http://mbientlab.com/contact/).
