### ISSUE TITLE
install script not working

### ISSUE THREAD

**Issue by ClementBarbisan** [mbientlab/MetaWear-SDK-JavaScript#7]
Hello,
When i try to do a "npm install metawear", i got this output :
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metawear@0.1.2 install: `make OPT_FLAGS=-Wno-strict-aliasing -C MetaWear-SDK-Cpp/ -j`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metawear@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can you tell me please what i did wrong?
Thanks

**Comment by scaryghost** [comment]
Please provide the entire npm output.

**Comment by ClementBarbisan** [comment]
So i figure i didn't had make, but now i have this log:
246 warn optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules\xpc-connection):
247 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
248 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
248 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
248 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
248 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
249 verbose stack Error: metawear@0.1.2 install: `make OPT_FLAGS=-Wno-strict-aliasing -C MetaWear-SDK-Cpp/ -j`
249 verbose stack Exit status 3221225781
249 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
249 verbose stack     at emitTwo (events.js:126:13)
249 verbose stack     at EventEmitter.emit (events.js:214:7)
249 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
249 verbose stack     at emitTwo (events.js:126:13)
249 verbose stack     at ChildProcess.emit (events.js:214:7)
249 verbose stack     at maybeClose (internal/child_process.js:925:16)
249 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
250 verbose pkgid metawear@0.1.2
251 verbose cwd E:\SDK-JavaScript
252 verbose Windows_NT 10.0.16299
253 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "metawear"
254 verbose node v8.9.4
255 verbose npm  v5.6.0
256 error code ELIFECYCLE
257 error errno 3221225781
258 error metawear@0.1.2 install: `make OPT_FLAGS=-Wno-strict-aliasing -C MetaWear-SDK-Cpp/ -j`
258 error Exit status 3221225781
259 error Failed at the metawear@0.1.2 install script.
259 error This is probably not a problem with npm. There is likely additional logging output above.
260 verbose exit [ 3221225781, true ]

I'm on windows 10 so maybe it has something to do with it.

**Comment by scaryghost** [comment]
The JavaScript SDK has not been tested for Windows and is originally intended for use on Linux.  We have a [C# SDK](https://github.com/mbientlab/MetaWear-SDK-CSharp) for Win10 devices.

**Comment by JpEncausse** [comment]
Got the same issue on windows, the installation fail because the script is looking for "make", i assume, to compile the C code. Would it be possible to download the pre-build dll for win32 / win64 ?

BTW, node-gyp evolved very well, and Noble is now simpler to install and see Metaware devices :-)

**Comment by scaryghost** [comment]
You can build the underlying C++ code with MSBuild:

https://github.com/mbientlab/MetaWear-SDK-Cpp#visual-studio-2017
