### ISSUE TITLE
Error when installing sdk on Mac

### ISSUE THREAD

**Issue by nayfusaurus** [mbientlab/MetaWear-SDK-JavaScript#9]
The error log is in pastebin:
[https://pastebin.com/705EmKUA](https://pastebin.com/705EmKUA)

My current setup is as follows:
Mac: v10.13.6
node: v8.11.3
npm: v5.6.0
metawear: v0.2.0
g++: 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Please assist,

Thank you!

**Comment by nayfusaurus** [comment]
@scaryghost 

I have updated the gcc version in my mac through macports following the steps mentioned here:
[http://www.cs.millersville.edu/~gzoppetti/InstallingGccMac.html](http://www.cs.millersville.edu/~gzoppetti/InstallingGccMac.html)

I have checked the gcc version as follows:

`Dariusa:MCMP dariusa$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin17/5.5.0/lto-wrapper
Target: x86_64-apple-darwin17
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc5/gcc5/work/gcc-5.5.0/configure --prefix=/opt/local --build=x86_64-apple-darwin17 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc5 --includedir=/opt/local/include/gcc5 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-5 --with-libiconv-prefix=/opt/local --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-5 --with-gxx-include-dir=/opt/local/include/gcc5/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local/libexec/isl18 --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --disable-tls --with-pkgversion='MacPorts gcc5 5.5.0_3'
Thread model: posix
gcc version 5.5.0 (MacPorts gcc5 5.5.0_3)`

However when installing metawear again, I encounted a similar issue and pasted below:
[https://pastebin.com/nmnZRTW1](https://pastebin.com/nmnZRTW1)

**Comment by scaryghost** [comment]
According to the 2nd error log, you are failing to compile the [node-gyp](https://github.com/nodejs/node-gyp) module.  You'll need to resolve the incompatibilities between that module and your dev environment.
